name: mobile_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.0.0
  lucide_icons: ^0.257.0
  cupertino_icons: ^1.0.8
  fl_chart: ^0.63.0 
  flutter_native_splash: ^2.4.4
  just_audio: ^0.9.36

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/  # <-- TAMBAHKAN INI